import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const colors = {
  primary: '#4C307A',
  secondary: '#A88AD3',
  accent: '#7B5EA7',
  darkPurple: '#2E1E43',
  lightPurple: '#CBB7E2',
  veryLightPurple: '#EDE5F7',
  inputBg: '#F7F4FB',
  inputBorder: '#E8DFF5',
  textDark: '#2E1E43',
  textMedium: '#5A4570',
  textLight: '#8A7B9C',
  white: '#FFFFFF',
  success: '#388E3C',
  successBg: '#F0FFF4',
  successBorder: '#C8FFD4',
  warning: '#E8A838',
  error: '#E06060',
  errorBg: '#FFF0F0',
  errorBorder: '#FFC8C8',
  info: '#0288D1',
  infoBg: '#F0F9FF',
  infoBorder: '#C8E5FF',
  navBar: '#D5C6E6',
  navTextActive: '#4C307A',
  navTextInactive: '#8A72A6',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  bgBeranda: {
    backgroundColor: colors.white,
  },
  bgTren: {
    backgroundColor: colors.secondary,
  },
  bgPengaturan: {
    backgroundColor: colors.secondary,
  },
  bgRiwayat: {
    backgroundColor: colors.white,
  },
  scrollContainer: {
    paddingBottom: 100,
  },

  // ==================== BERANDA ====================
  header: {
    backgroundColor: colors.lightPurple,
    paddingTop: 45,
    paddingBottom: 35,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    alignItems: 'center',
  },
  headerTitle: {
    color: colors.white,
    fontSize: 26,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 8,
  },
  headerSubtitle: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '400',
    textAlign: 'center',
  },
  content: {
    paddingHorizontal: 20,
    marginTop: 20,
  },
  phaseCard: {
    backgroundColor: colors.secondary,
    borderRadius: 20,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  phaseCardAlert: {
    backgroundColor: '#FF8A8A',
  },
  phaseCardLeft: {
    flex: 1,
  },
  phaseCardLabel: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  phaseCardValue: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '400',
  },
  phaseCardValueAlert: {
    color: '#8A0000',
  },
  phaseCardRight: {
    alignItems: 'flex-end',
  },
  phaseCardDurationLabel: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '300',
    marginBottom: 4,
  },
  phaseCardDurationValue: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '800',
  },
  phaseCardDurationValueAlert: {
    color: '#8A0000',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  gridCard: {
    backgroundColor: colors.secondary,
    borderRadius: 18,
    padding: 16,
    width: (width - 55) / 2,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 3,
  },
  gridIconImg: {
    width: 28,
    height: 28,
    marginBottom: 10,
    tintColor: colors.white,
  },
  gridCardLabel: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '300',
    marginBottom: 4,
  },
  gridCardValue: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '800',
  },
  alertCard: {
    backgroundColor: colors.secondary,
    borderRadius: 20,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 3,
  },
  alertCardAnomaly: {
    backgroundColor: colors.errorBg,
    borderColor: colors.errorBorder,
    borderWidth: 1,
  },
  alertCardGated: {
    backgroundColor: colors.infoBg,
    borderColor: colors.infoBorder,
    borderWidth: 1,
  },
  alertCardNormal: {
    backgroundColor: colors.successBg,
    borderColor: colors.successBorder,
    borderWidth: 1,
  },
  alertIconContainer: {
    marginRight: 16,
  },
  alertIconImg: {
    width: 36,
    height: 36,
    tintColor: colors.white,
  },
  alertTextContainer: {
    flex: 1,
  },
  alertTitle: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 6,
  },
  alertTitleAnomaly: {
    color: '#D32F2F',
  },
  alertTitleGated: {
    color: colors.info,
  },
  alertTitleNormal: {
    color: colors.success,
  },
  alertDesc: {
    color: colors.white,
    fontSize: 13,
    lineHeight: 18,
  },
  alertDescAnomaly: {
    color: '#C62828',
  },
  alertDescGated: {
    color: '#01579B',
  },
  alertDescNormal: {
    color: '#1B5E20',
  },
  progressSection: {
    marginBottom: 10,
  },
  progressTitle: {
    color: colors.darkPurple,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 18,
  },
  ringsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 5,
  },
  ringWrapper: {
    alignItems: 'center',
  },
  ringDayText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  ringOuter: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ringInner: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.white,
  },
  ringPercentText: {
    color: colors.darkPurple,
    fontSize: 9,
    fontWeight: 'bold',
    marginTop: 6,
  },

  // ==================== TREN ====================
  trenContainer: {
    paddingHorizontal: 20,
  },
  trenHeader: {
    alignItems: 'center',
    paddingTop: 45,
    paddingBottom: 15,
  },
  trenHeaderTitle: {
    color: colors.white,
    fontSize: 26,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: -30,
    marginBottom: 4,
    marginLeft: -200,
  },
  trenHeaderSubtitle: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '400',
    textAlign: 'center',
    marginLeft: -188,
    opacity: 0.9,
  },
  segmentedControl: {
    flexDirection: 'row',
    backgroundColor: 'rgba(76, 48, 122, 0.4)',
    borderRadius: 24,
    padding: 4,
    marginBottom: 20,
    justifyContent: 'space-between',
  },
  segmentBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 20,
  },
  segmentBtnActive: {
    backgroundColor: colors.white,
  },
  segmentText: {
    fontSize: 14,
    fontWeight: '600',
  },
  segmentTextActive: {
    color: colors.primary,
  },
  segmentTextInactive: {
    color: colors.white,
    opacity: 0.8,
  },
  chartCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  chartCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  chartCardIconImg: {
    width: 22,
    height: 22,
    marginRight: 8,
  },
  chartCardTitle: {
    color: colors.darkPurple,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  chartWrapper: {
    alignItems: 'center',
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  statCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 16,
    width: (width - 55) / 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 3,
  },
  statLabel: {
    color: colors.textLight,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 6,
  },
  statValue: {
    color: colors.primary,
    fontSize: 24,
    fontWeight: '800',
  },
  statUnit: {
    fontSize: 14,
    fontWeight: '400',
    color: colors.textLight,
  },

  // ==================== BOTTOM NAV ====================
  navBar: {
    minHeight: 70,
    backgroundColor: colors.navBar,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 8,
    paddingBottom: 0,
    borderTopWidth: 1,
    borderTopColor: 'rgba(76, 48, 122, 0.12)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 10,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingVertical: 4,
  },
  navIconImg: {
    width: 24,
    height: 24,
    marginBottom: 3,
  },
  navIconActive: {
    opacity: 1,
  },
  navIconInactive: {
    opacity: 0.45,
  },
  navText: {
    fontSize: 11,
    fontWeight: 'bold',
  },
  navTextActive: {
    color: colors.navTextActive,
  },
  navTextInactive: {
    color: colors.navTextInactive,
  },

  // ==================== PENGATURAN ====================
  pengaturanContainer: {
    paddingTop: 50,
    paddingHorizontal: 20,
  },
  pengaturanTitle: {
    color: colors.white,
    fontSize: 30,
    fontWeight: '800',
    marginTop: -20,
    marginBottom: 24,
  },
  profileCard: {
    alignItems: 'center',
    marginBottom: 28,
  },
  avatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.navBar,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 3,
    borderColor: colors.white,
  },
  avatarEmoji: {
    fontSize: 38,
  },
  profileName: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 4,
  },
  profileRole: {
    color: colors.white,
    fontSize: 14,
    opacity: 0.85,
  },
  settingSection: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingBottom: 16,
    marginBottom: 16,
  },
  settingSectionLabel: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    opacity: 0.75,
    paddingTop: 14,
    paddingBottom: 8,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.2)',
  },
  settingRowNoBorder: {
    borderBottomWidth: 0,
  },
  settingRowLeft: {
    flex: 1,
  },
  settingRowTitle: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 3,
  },
  settingRowTitleBold: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '800',
  },
  settingRowSub: {
    color: colors.white,
    fontSize: 12,
    opacity: 0.75,
  },
  settingRowIcon: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '300',
    opacity: 0.9,
  },
  settingRowChevron: {
    color: colors.white,
    fontSize: 26,
    fontWeight: '300',
    opacity: 0.9,
  },
  toggle: {
    width: 48,
    height: 28,
    borderRadius: 14,
    padding: 3,
    justifyContent: 'center',
  },
  toggleOn: {
    backgroundColor: colors.primary,
  },
  toggleOff: {
    backgroundColor: 'rgba(255,255,255,0.35)',
  },
  toggleThumb: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.white,
  },
  toggleThumbOn: {
    alignSelf: 'flex-end',
  },
  toggleThumbOff: {
    alignSelf: 'flex-start',
  },

  // ==================== RIWAYAT ====================
  riwayatContainer: {
    paddingTop: 50,
    paddingHorizontal: 20,
  },
  riwayatTitle: {
    color: colors.darkPurple,
    fontSize: 22,
    fontWeight: '800',
    marginTop: -20,
    marginBottom: 10,
  },
  riwayatSubtitle: {
    color: colors.textLight,
    fontSize: 16,
    fontWeight: '500',
    marginTop: -10,
    marginBottom: 24,
  },
  riwayatCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.veryLightPurple,
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
  },
  riwayatIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
    flexShrink: 0,
  },
  riwayatIconStabil: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: '#6BBF8A',
  },
  riwayatIconManik: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.warning,
  },
  riwayatIconDepresi: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.error,
  },
  riwayatIconText: {
    fontSize: 18,
  },
  riwayatCardText: {
    flex: 1,
  },
  riwayatCardTitle: {
    color: colors.darkPurple,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  riwayatCardSub: {
    color: colors.textLight,
    fontSize: 12,
    fontWeight: '500',
  },

  // ==================== SPLASH SCREEN ====================
  splashContainer: {
    flex: 1,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  splashLogo: {
    width: width * 0.62,
    height: width * 0.85,
  },
  splashAbsolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
  },

  // ==================== EDUKASI ====================
  eduSection: {
    marginTop: 28,
    paddingBottom: 8,
  },
  eduSectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.darkPurple,
    marginBottom: 2,
  },
  eduSectionSubtitle: {
    fontSize: 12,
    color: colors.textLight,
    marginBottom: 16,
    fontWeight: '400',
  },
  eduCard: {
    backgroundColor: colors.white,
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 16,
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  eduThumbnail: {
    width: '100%',
    height: 170,
    backgroundColor: colors.veryLightPurple,
  },
  eduCardBody: {
    padding: 14,
  },
  eduCardTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1A2E',
    marginBottom: 6,
    lineHeight: 21,
  },
  eduCardExcerpt: {
    fontSize: 13,
    color: colors.textMedium,
    lineHeight: 19,
    marginBottom: 10,
  },
  eduCardSource: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  eduSourceName: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.darkPurple,
  },
  eduSourceUrl: {
    fontSize: 11,
    color: '#9B8CB0',
    flex: 1,
  },
  eduDetail: {
    marginTop: 12,
    paddingBottom: 20,
  },
  eduDetailBack: {
    paddingVertical: 8,
    paddingHorizontal: 4,
    marginBottom: 12,
    alignSelf: 'flex-start',
  },
  eduDetailBackText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.accent,
  },
  eduDetailThumbnail: {
    width: '100%',
    height: 200,
    borderRadius: 14,
    backgroundColor: colors.veryLightPurple,
    marginBottom: 16,
  },
  eduDetailBody: {
    paddingHorizontal: 2,
  },
  eduDetailTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1A2E',
    lineHeight: 25,
    marginBottom: 10,
  },
  eduDetailSourceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  eduDetailSourceName: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.accent,
  },
  eduDetailContent: {
    fontSize: 14,
    color: '#3A2E4A',
    lineHeight: 22,
    marginBottom: 20,
  },
  eduDetailUrlRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    backgroundColor: '#F3EEF9',
    borderRadius: 8,
    padding: 10,
  },
  eduDetailUrlLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMedium,
  },
  eduDetailUrl: {
    fontSize: 12,
    color: colors.accent,
    flex: 1,
  },

  // ==================== LOCK SCREEN ====================
  lockContainerAbsolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.white,
    zIndex: 100,
  },
  lockLogo: {
    width: 90,
    height: 90,
    marginBottom: 24,
  },
  lockTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.darkPurple,
    marginBottom: 4,
  },
  lockSubtitle: {
    fontSize: 13,
    color: colors.textLight,
    marginBottom: 28,
  },
  lockDotsRow: {
    flexDirection: 'row',
    gap: 18,
    marginBottom: 12,
  },
  lockDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  lockDotEmpty: {
    backgroundColor: '#E8E0F0',
    borderWidth: 1.5,
    borderColor: '#D0C4DE',
  },
  lockDotFilled: {
    backgroundColor: colors.accent,
    borderWidth: 0,
  },
  lockDotError: {
    backgroundColor: colors.error,
    borderWidth: 0,
  },
  lockErrorText: {
    fontSize: 13,
    color: colors.error,
    fontWeight: '500',
    marginBottom: 8,
  },
  lockKeypad: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    width: 260,
    marginTop: 16,
  },
  lockKey: {
    width: 72,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 6,
    borderRadius: 16,
    backgroundColor: '#F3EEF9',
  },
  lockKeyEmpty: {
    width: 72,
    height: 60,
    margin: 6,
  },
  lockKeyText: {
    fontSize: 26,
    fontWeight: '600',
    color: colors.darkPurple,
  },
  lockKeyDelIcon: {
    width: 26,
    height: 26,
  },
  lockBiometric: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 24,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: '#F3EEF9',
  },
  lockBiometricText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.accent,
  },

  // ==================== REMINDERS ====================
  reminderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.2)',
  },
  reminderRowNoBorder: {
    borderBottomWidth: 0,
    paddingBottom: 6,
  },
  reminderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  reminderMeta: {
    justifyContent: 'center',
  },
  reminderTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.white,
    marginBottom: 2,
  },
  reminderTime: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.7)',
    fontWeight: '500',
  },
  reminderRightActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  deleteReminderTextBtn: {
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  deleteReminderText: {
    fontSize: 12,
    color: '#cd0014ff',
    fontWeight: '600',
  },
  addReminderBtn: {
    marginTop: 16,
    paddingVertical: 10,
    borderWidth: 1.5,
    borderColor: colors.accent,
    borderStyle: 'dashed',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addReminderBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.accent,
  },
  addReminderForm: {
    marginTop: 16,
    padding: 16,
    backgroundColor: colors.inputBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.inputBorder,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#5C447C',
    marginBottom: 6,
    marginTop: 10,
  },
  formInput: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#DCD3EA',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    color: colors.darkPurple,
  },
  formTypeRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  formTypeBtn: {
    flex: 1,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#DCD3EA',
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formTypeBtnActive: {
    backgroundColor: '#E2D9F3',
    borderColor: colors.accent,
  },
  formTypeBtnText: {
    fontSize: 13,
    color: colors.textLight,
    fontWeight: '600',
  },
  formTypeBtnTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  formActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 18,
  },
  formCancelBtn: {
    flex: 1,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#DCD3EA',
  },
  formCancelBtnText: {
    fontSize: 13,
    color: colors.textLight,
    fontWeight: '600',
  },
  formSaveBtn: {
    flex: 1,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.accent,
  },
  formSaveBtnText: {
    fontSize: 13,
    color: colors.white,
    fontWeight: '700',
  },

  // ==================== BLE MODAL ====================
  bleModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
  bleModalContent: {
    width: width - 40,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    maxHeight: '80%',
  },
  bleModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.darkPurple,
    marginBottom: 8,
    textAlign: 'center',
  },
  bleModalStatus: {
    fontSize: 14,
    color: colors.accent,
    marginBottom: 16,
    textAlign: 'center',
    fontWeight: '500',
  },
  bleDeviceList: {
    maxHeight: 250,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 8,
    backgroundColor: colors.inputBg,
  },
  bleDeviceItem: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.inputBorder,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bleDeviceName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.darkPurple,
  },
  bleDeviceAddress: {
    fontSize: 12,
    color: colors.textLight,
    marginTop: 2,
  },
  bleDeviceConnectText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.accent,
  },
  bleEmptyText: {
    fontSize: 14,
    color: colors.textLight,
    textAlign: 'center',
    padding: 20,
    fontStyle: 'italic',
  },
  bleScanBtn: {
    backgroundColor: colors.accent,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 8,
  },
  bleScanBtnText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  bleCloseBtn: {
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  bleCloseBtnText: {
    color: colors.accent,
    fontWeight: '600',
    fontSize: 15,
  },
  bleConnectedContainer: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  bleConnectedText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.darkPurple,
    marginBottom: 20,
  },
  bleDisconnectBtn: {
    backgroundColor: '#FF5E5E',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
  },
  bleDisconnectBtnText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: 15,
  },

  // ==================== EMERGENCY CONTACTS ====================
  emergencyContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.2)',
  },
  emergencyContactRowLast: {
    borderBottomWidth: 0,
  },
  emergencyContactAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  emergencyContactAvatarText: {
    fontSize: 18,
    color: colors.white,
    fontWeight: '700',
  },
  emergencyContactInfo: {
    flex: 1,
  },
  emergencyContactName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.white,
    marginBottom: 2,
  },
  emergencyContactPhone: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.7)',
    fontWeight: '500',
  },
  actionModalOverlay: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
    zIndex: 9999,
  },
  actionModalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 30,
    width: '100%',
  },
  actionModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E8DFF5',
  },
  actionModalAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.veryLightPurple,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  actionModalAvatarText: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.accent,
  },
  actionModalName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.darkPurple,
    marginBottom: 2,
  },
  actionModalPhone: {
    fontSize: 13,
    color: colors.textLight,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 8,
  },
  actionButtonCall: {
    backgroundColor: '#E8F5E9',
  },
  actionButtonSms: {
    backgroundColor: '#E3F2FD',
  },
  actionButtonWhatsapp: {
    backgroundColor: '#E8F5E9',
  },
  actionButtonDelete: {
    backgroundColor: '#FFEBEE',
  },
  actionButtonCancel: {
    backgroundColor: '#F5F5F5',
    marginTop: 4,
  },
  actionButtonIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  actionButtonText: {
    fontSize: 15,
    fontWeight: '600',
  },
  actionButtonTextCall: {
    color: '#2E7D32',
  },
  actionButtonTextSms: {
    color: '#1565C0',
  },
  actionButtonTextWhatsapp: {
    color: '#2E7D32',
  },
  actionButtonTextDelete: {
    color: '#C62828',
  },
  actionButtonTextCancel: {
    color: colors.textLight,
    textAlign: 'center' as const,
  },
});
